site_name: WekaDeeplearning4j
theme: readthedocs
repo_url: https://github.com/Waikato/wekaDeeplearning4j
site_description: WekaDeeplearning4j Documentation
pages:
    - Home: index.md
    - Installation: install.md

    - User Guide:
        - 'Classifying iris': 'user-guide/classifying-iris.md'
    - About: about.md
